version: '3'
services:
  emby-telegram-notifier:
    container_name: emby-telegram-notifier
    image: fahmula/emby-telegram-notifier
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - EMBY_BASE_URL=${EMBY_BASE_URL}
      - EMBY_API_KEY=${EMBY_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - SEASON_ADDED_WITHIN_X_DAYS=${SEASON_ADDED_WITHIN_X_DAYS}
      - EPISODE_PREMIERED_WITHIN_X_DAYS=${EPISODE_PREMIERED_WITHIN_X_DAYS}
    env_file:
      - .env